workflows:
  macos-distribution:
    name: macOS Distribution
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - code-signing
      vars:
        BUNDLE_ID: "com.denice.agent.ai"
        XCODE_SCHEME: "AiAssistant"
        XCODE_WORKSPACE: "AiAssistant.xcworkspace"
      xcode: latest
      cocoapods: default

    integrations:
      app_store_connect: Denice-CI-CD-Key

    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install

      - name: Set up keychain for code signing
        script: |
          keychain initialize

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --platform MAC_OS \
            --type MAC_APP_STORE \
            --create

      - name: Fetch Mac Installer Distribution certificates
        script: |
          app-store-connect certificates list --type MAC_APP_DISTRIBUTION --save || \
          app-store-connect certificates create --type MAC_APP_DISTRIBUTION --save

      - name: Add certificates to keychain
        script: |
          keychain add-certificates
          keychain list-certificates | jq '.[] | .common_name'

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: Build .app using Xcode workspace
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -derivedDataPath build \
            clean build

      - name: Create signed .pkg installer
        script: |
          set -xe

          APP_NAME=$(find build -name "*.app" | head -n 1)
          if [ ! -d "$APP_NAME" ]; then
            echo "❌ ERROR: .app not found at expected location"
            exit 1
          fi

          PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg
          xcrun productbuild --component "$APP_NAME" /Applications/ unsigned.pkg

          INSTALLER_CERT_NAME=$(keychain list-certificates | jq '.[]
            | select(.common_name | contains("Developer ID Installer")) 
            | .common_name' | xargs)

          if [ -z "$INSTALLER_CERT_NAME" ]; then
            echo "❌ ERROR: Could not find 'Developer ID Installer' certificate"
            exit 1
          fi

          echo "✅ Using certificate: $INSTALLER_CERT_NAME"
          xcrun productsign --sign "$INSTALLER_CERT_NAME" unsigned.pkg "$PACKAGE_NAME"
          rm -f unsigned.pkg

      - name: Notarize the .pkg installer
        script: |
          PKG_FILE=$(find . -name "*.pkg" | head -n 1)
          xcrun notarytool submit "$PKG_FILE" \
            --apple-id "$APPLE_ID" \
            --team-id "$TEAM_ID" \
            --password "$APPLE_ID_PASSWORD" \
            --wait \
            --force

    artifacts:
      - build/**/*.app
      - build/**/*.pkg
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - esmondandersonhaldegallagher@gmail.com
        notify:
          success: true
          failure: true