workflows:
  macos-distribution:
    name: macOS Distribution
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - code-signing
      vars:
        BUNDLE_ID: "com.denice.agent.ai"
        XCODE_WORKSPACE: "AiAssistant.xcworkspace"
        XCODE_SCHEME: "AiAssistant"
      xcode: latest
      cocoapods: default

    integrations:
      app_store_connect: Denice-CI-CD-Key

    scripts:
      - name: Install Codemagic CLI tools
        script: pip3 install codemagic-cli-tools

      - name: Install CocoaPods dependencies
        script: |
          gem install cocoapods # optional if not cached
          pod install

      - name: Set up keychain to be used for code signing
        script: keychain initialize

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --platform MAC_OS \
            --type MAC_APP_STORE \
            --create

      - name: Fetch Mac Installer Distribution certificates
        script: |
          app-store-connect certificates list --type MAC_APP_DISTRIBUTION --save || \
          app-store-connect certificates create --type MAC_APP_DISTRIBUTION --save

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Set up code signing settings
        script: xcode-project use-profiles

      - name: Build .app for macOS
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -derivedDataPath build \
            clean build

      - name: Create signed .pkg installer
        script: |
          set -x
          APP_NAME=$(find build -name "*.app" | head -n 1)
          PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg
          xcrun productbuild --component "$APP_NAME" /Applications/ unsigned.pkg

          INSTALLER_CERT_NAME=$(keychain list-certificates | jq '.[]
            | select(.common_name | contains("Developer ID Installer")) 
            | .common_name' | xargs)

          xcrun productsign --sign "$INSTALLER_CERT_NAME" unsigned.pkg "$PACKAGE_NAME"
          rm -f unsigned.pkg

      - name: Notarize the .pkg installer
        script: |
          PKG_FILE=$(find . -name "*.pkg")
          xcrun notarytool submit "$PKG_FILE" \
            --apple-id "$APPLE_ID" \
            --team-id "$TEAM_ID" \
            --password "$APPLE_ID_PASSWORD" \
            --wait

    artifacts:
      - build/**/*.app
      - build/**/*.pkg
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - esmondandersonhaldegallagher@gmail.com
        notify:
          success: true
          failure: true