workflows:
  macos-distribution:
    name: macOS Distribution
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - code-signing
      vars:
        BUNDLE_ID: "com.denice.agent.ai"
        XCODE_SCHEME: "AiAssistant"
        XCODE_WORKSPACE: "AiAssistant.xcworkspace"
      xcode: latest
      cocoapods: default

    integrations:
      app_store_connect: Denice-CI-CD-Key

    scripts:
      - name: Install CocoaPods dependencies
        script: pod install

      - name: Set up keychain for code signing
        script: |
          keychain initialize
          echo "🔐 Initialized keychain."

      - name: Fetch signing files for .app signing
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --platform MAC_OS \
            --type MAC_APP_STORE \
            --create || true

      # - name: Ensure Mac Installer Distribution certificate is available
      #   script: |
      #     app-store-connect certificates list --type MAC_INSTALLER_DISTRIBUTION --save || \
      #     app-store-connect certificates create --type MAC_INSTALLER_DISTRIBUTION --save

      - name: Import Developer ID Application certificate and key
        script: |
          echo "$MAC_CERT_CRT" > dev_id_app.crt
          echo "$MAC_CERT_KEY" > dev_id_app.key
          openssl pkcs12 -export \
            -inkey dev_id_app.key \
            -in dev_id_app.crt \
            -out dev_id_app.p12 \
            -passout pass:denice123
          security import dev_id_app.p12 -k "$(keychain list-keychains | head -1 | tr -d '"')" -P denice123 -T /usr/bin/codesign

      - name: Import Developer ID Installer certificate and key
        script: |
          echo "$INSTALLER_CERT_CRT" > dev_id_inst.crt
          echo "$INSTALLER_CERT_KEY" > dev_id_inst.key
          openssl pkcs12 -export \
            -inkey dev_id_inst.key \
            -in dev_id_inst.crt \
            -out dev_id_inst.p12 \
            -passout pass:denice123
          security import dev_id_inst.p12 -k "$(keychain list-keychains | head -1 | tr -d '"')" -P denice123 -T /usr/bin/codesign

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: Build .app using Xcode workspace
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -derivedDataPath build \
            clean build

      - name: Create signed .pkg installer
        script: |
          set -xe

          APP_NAME=$(find build -name "*.app" | head -n 1)
          if [ ! -d "$APP_NAME" ]; then
            echo "❌ ERROR: .app not found at expected location"
            exit 1
          fi

          PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg
          xcrun productbuild --component "$APP_NAME" /Applications/ unsigned.pkg

          INSTALLER_CERT_NAME="Developer ID Installer: Angelle Denice (K9MTJ7767Q)"
          echo "✅ Using certificate: $INSTALLER_CERT_NAME"
          xcrun productsign --sign "$INSTALLER_CERT_NAME" unsigned.pkg "$PACKAGE_NAME"
          rm -f unsigned.pkg

      - name: Notarize the .pkg installer
        script: |
          PKG_FILE=$(find . -name "*.pkg" | head -n 1)
          if [ -z "$PKG_FILE" ]; then
            echo "❌ ERROR: .pkg file not found"
            exit 1
          fi

          xcrun notarytool submit "$PKG_FILE" \
            --apple-id "$APPLE_ID" \
            --team-id "$TEAM_ID" \
            --password "$APPLE_ID_PASSWORD" \
            --wait \
            --force

    artifacts:
      - build/**/*.app
      - build/**/*.pkg
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - esmondandersonhaldegallagher@gmail.com
        notify:
          success: true
          failure: true