workflows:
  macos-sign-app:
    name: macOS Sign .app Only
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - code-signing
      vars:
        BUNDLE_ID: "com.denice.agent.ai"
        XCODE_SCHEME: "AiAssistant"
        XCODE_WORKSPACE: "AiAssistant.xcworkspace"
      xcode: latest
      cocoapods: default

    integrations:
      app_store_connect: Denice-CI-CD-Key

    scripts:
      - name: Install CocoaPods dependencies
        script: pod install

      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize

      # - name: Fetch signing files
      #   script: |
      #     app-store-connect fetch-signing-files "$BUNDLE_ID" \
      #       --platform MAC_OS \
      #       --type DEVELOPER_ID_APPLICATION \
      #       --create

      - name: Fetch Developer ID Application certificate
        script: |
          app-store-connect certificates list --type DEVELOPER_ID_APPLICATION --save || \
          app-store-connect certificates create --type DEVELOPER_ID_APPLICATION --save

      - name: Set up signing certificate
        script: keychain add-certificates

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: Build and sign the .app using Xcode
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -derivedDataPath build \
            clean build

          APP_PATH=$(find build -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "❌ ERROR: .app not found"
            exit 1
          fi

          echo "✅ Found app: $APP_PATH"

          codesign --deep --force --verbose --options runtime \
            --sign "Developer ID Application: Angelle Denice (K9MTJ7767Q)" \
            "$APP_PATH"

          ditto -c -k --keepParent "$APP_PATH" signed_app.zip

    artifacts:
      - build/**/*.app
      - signed_app.zip

    publishing:
      email:
        recipients:
          - esmondandersonhaldegallagher@gmail.com
        notify:
          success: true
          failure: true