workflows:
  macos-distribution:
    name: macOS Distribution
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      groups:
        - code-signing
      vars:
        BUNDLE_ID: "com.denice.agent.ai"
        XCODE_SCHEME: "AiAssistant"
        XCODE_WORKSPACE: "AiAssistant.xcworkspace"
      xcode: latest
      cocoapods: default

    integrations:
      app_store_connect: Denice-CI-CD-Key

    scripts:
      - name: Install CocoaPods dependencies
        script: pod install

      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: | 
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --platform MAC_OS \
            --type MAC_APP_STORE \
            --create
      - name: Fetch Mac Installer Distribution certificates
        script: |  
            app-store-connect certificates list --type MAC_APP_DISTRIBUTION --save || \
            app-store-connect certificates create --type MAC_APP_DISTRIBUTION --save
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: Package application
        script: | 
          set -x
        
          # Command to find the path to your generated app, may be different
          APP_NAME=$(find $(pwd) -name "*.app")  
          cd $(dirname "$APP_NAME")
        
          PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg
          xcrun productbuild --component "$APP_NAME" /Applications/ unsigned.pkg  # Create and unsigned package

          # Find the installer certificate common name in keychain
          INSTALLER_CERT_NAME=$(keychain list-certificates \
            | jq '.[]
            | select(.common_name
            | contains("Mac Developer Installer"))
            | .common_name' \
            | xargs)
          
          xcrun productsign --sign "$INSTALLER_CERT_NAME" unsigned.pkg "$PACKAGE_NAME" # Sign the package
        
          rm -f unsigned.pkg               

      - name: Notarize the .pkg installer
        script: |
          PKG_FILE=$(find . -name "*.pkg" | head -n 1)
          if [ -z "$PKG_FILE" ]; then
            echo "❌ ERROR: .pkg file not found"
            exit 1
          fi

          xcrun notarytool submit "$PKG_FILE" \
            --apple-id "$APPLE_ID" \
            --team-id "$TEAM_ID" \
            --password "$APPLE_ID_PASSWORD" \
            --wait \
            --force

    artifacts:
      - build/**/*.app
      - build/**/*.pkg
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - esmondandersonhaldegallagher@gmail.com
        notify:
          success: true
          failure: true